name: CI-Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'src/**/**.md'
      - 'Makefiles/**'
      - 'nix/**'
      - 'book/**'
  pull_request:
    paths-ignore:
       - '**.md'
       - 'book/**'
       - 'src/**/**.md'
       - 'Makefiles/**'
       - 'nix/**'
       - 'book/**'

env:
  RUST_LATEST_STABLE_VERSION: 1.65
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  catalyst-core-tests:
    name: Catalyst Core Tests
    runs-on: ubuntu-latest
    env:
      CARGO_FLAGS: --verbose --locked
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: Swatinem/rust-cache@v2
      - name: Install Nextest
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - name: Install deps
        run:
          sudo apt install -y protobuf-compiler libssl-dev libpq-dev libsqlite3-dev pkg-config
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{env.RUST_LATEST_STABLE_VERSION}}
      - name: Build Catalyst Core tests
        run:
          cargo build -p vit-servicing-station-cli -p vit-servicing-station-server -p jcli -p jormungandr -p explorer
      - name: Run Catalyst Core tests
        run:
          cargo nextest run --profile ci

  wallet-js-binding:
    name: Wallet JS Binding Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'

    - name: Build wasm package
      run: |
        cd src/chain-wallet-libs/bindings/wallet-wasm-js
        wasm-pack build --release --target=nodejs -d pkg

    - name: Build JS package
      run: |
        cd src/chain-wallet-libs/bindings/wallet-wasm-js/js
        rm package.json
        cp package_test.json package.json
        npm install

    - name: Run JS tests
      run: |
        cd src/chain-wallet-libs/bindings/wallet-wasm-js/js-test
        npm install
        npm test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: Swatinem/rust-cache@v2
      - name: Install deps
        run:
          sudo apt install -y protobuf-compiler libssl-dev libpq-dev libsqlite3-dev pkg-config
      - name: Clippy and fmt
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{env.RUST_LATEST_STABLE_VERSION}}
          components: rustfmt, clippy
      - run: scripts/check-fmt.sh