name: GitHub Pages

on: 
  push:

  pull_request:
    paths:
      - 'book/src/**'
      - '**.md'
      - 'LICENSE-APACHE'
      - 'LICENSE-MIT'
      - 'src/jormungandr/jormungandr-lib/src/interfaces/block0_configuration/BLOCKCHAIN_CONFIGURATION_DOCUMENTED_EXAMPLE.yaml'
      - 'src/jormungandr/jormungandr-lib/src/interfaces/CONFIG_PARAMS_DOCUMENTED_EXAMPLE.yaml'
      - 'book.toml'
      - 'Makefile.toml'
      - 'Makefiles/docs.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PUBLISH_DOCS: ${{ github.event_name == 'push' }}
      GIT_BRANCH: ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}      
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Build Docs
        uses: docker://ghcr.io/input-output-hk/catalyst-gh-tools:v1.1
        with:
          entrypoint: cargo
          args: make build-docs

      # On PUSH we deploy docs to a sub-directory named after the branch.
      # But ONLY if a docs page changes.
      - name: Deploy Docs
        if: ${{ env.PUBLISH_DOCS }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
          destination_dir: ${{ GIT_BRANCH }}
