name: GitHub Pages

on: [push, pull_request]

jobs:
  deploy:
    name: Deploy GitHub Pages
    runs-on:  ubuntu-latest
    permissions:
      contents: write
      pull-requests: write  # To create a PR from that branch
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    # Service containers to run
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout The Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set env
        run: |
          GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      - name: Start the Kroki service for building images
        run: docker-compose -f "utilities/kroki-service/docker-compose.yml" up -d --build

      - name: Build Docs
        uses: docker://ghcr.io/input-output-hk/catalyst-gh-tools:v1.4
        with:
          entrypoint: cargo
          args: make build-docs

      # On PUSH or PR we deploy docs to a sub-directory named after the branch.
      # This lets us review the docs as rendered, and not just the markdown.
      - name: Deploy Docs
        id:   deployAttempt
        continue-on-error: true
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
          destination_dir: ${{ env.GIT_BRANCH }}

      # This might fail if we try and deploy multiple pages at once.
      # So, check if it did, and retry.

      # Retry #1
      - name: Delay On Failure To Deploy
        id:   deployRetryWait1
        if:   steps.deployAttempt.outcome == 'failure'
        run: |
          sleep $[ ( $RANDOM % 10 )  + 1 ]s
        shell: bash

      - name: Deploy Docs
        id:   deployRetry1
        if:   steps.deployAttempt.outcome == 'failure'
        continue-on-error: true
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
          destination_dir: ${{ env.GIT_BRANCH }}

      # Retry #2
      - name: Delay On Failure To Deploy
        id:   deployRetryWait2
        if:   steps.deployRetry1.outcome == 'failure'
        run: |
          sleep $[ ( $RANDOM % 10 )  + 1 ]s
        shell: bash

      - name: Deploy Docs
        id:   deployRetry2
        if:   steps.deployRetry1.outcome == 'failure'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
          destination_dir: ${{ env.GIT_BRANCH }}

      - name: Stop containers
        if: always()
        run: docker-compose -f "utilities/kroki-service/docker-compose.yml" down