name: Test

on:
  push:

permissions:
  id-token: write
  contents: read
  packages: write

env:
  AWS_REGION: eu-central-1
  AWS_ROLE_ARN: arn:aws:iam::332405224602:role/ci
  EARTHLY_TARGET: docker
  EARTHLY_VERSION: 0.7.6
  ECR_REGISTRY: 332405224602.dkr.ecr.eu-central-1.amazonaws.com
  TAG: ${{ github.sha }}

jobs:
  discover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup CI
        uses: input-output-hk/catalyst-ci/actions/setup@actions-2.0
        with:
          aws_role_arn: ${{ env.AWS_ROLE_ARN }}
          aws_region: ${{ env.AWS_REGION }}
          earthly_version: ${{ env.EARTHLY_VERSION }}
      - name: See directory
        run: ls -la
